logging:
  config: classpath:log/log4j2.yml

server:
  port: 5400

#SnowflakeIdWorker配置(0-31)
snowflakeIdWorker:
  workerId: 1
  dataCenterId: 0

spring:
  application:
    name: security-service
  datasource:
    druid:
      base:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/newstandard?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
      initialSize: 10 #连接池初始化连接数
      minIdle: 20 #连接池最小连接数
      maxActive: 50 #连接池最大连接数
      maxWait: 60000 #获取连接等待超时的时间,单位是毫秒
      timeBetweenEvictionRunsMillis: 60000 #间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      minEvictableIdleTimeMillis: 300000 #连接在池中最小生存的时间,单位是毫秒
      validationQuery: SELECT 1 FROM DUAL #validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true #打开PSCache,并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j2 #监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: true #合并多个DruidDataSource的监控数据
  redis:
    host: localhost
    port: 6379
    #    sentinel:
    #      master:  mymaster
    #      nodes: 39.108.236.231:26379,60.205.205.204:26378,60.205.205.204:26379
    password: newStandard
    timeout: 5000ms
    database: 0
    lettuce:
      pool:
        max-wait: 1000ms
        max-active: 8
        max-idle: 8
        min-idle: 0

feign:
  hystrix:
    enabled: true

authentication:
  ssl:
    pfxFileName: private.pfx
    password: Aa123456